baseURL = 'https://www.lauratech.com/'
languageCode = 'en-us'
title = 'LauraTech'
sectionPagesMenu = 'main'

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'soho'
    
